import type { Metadata } from "next";
import "./globals.css";
import { Tinos } from 'next/font/google'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Tinos({ weight: ['400', '700'], subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${font.className} font-sans  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
