import type { Metadata } from "next";
import "./globals.css";
import { Tinos } from 'next/font/google'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
// config.autoAddCss = false


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Tinos({ weight: ['400', '700'] ,subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${font.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
