name: deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Stop and Remove Running Container
        run: |
          if [ $(docker ps -q -f name=new-site) ]; then
            docker stop new-site
            docker rm new-site
          fi

      - name: Delete Previous Images
        run: |
          docker rmi $(docker images -q new-site:latest) || true

      - name: Build New Image
        run: docker build -t new-site:latest .

      - name: Deploy New Image
        run: docker run -d --name new-site -p 3000:3000 new-site:latest